#!/bin/sh

SCRIPT_DIR=$(dirname "$0")
. "$SCRIPT_DIR/hook-lib.sh"

contains_wip() {
  echo "$1" | grep -i -E '(^|[^a-z0-9_])("wip"|\[wip\]|wip)([^a-z0-9_]|$)' >/dev/null
}

# First read stdin into a temp file
TEMP_FILE=$(mktemp)
cat >"$TEMP_FILE"

z40=0000000000000000000000000000000000000000
while read local_ref local_sha remote_ref remote_sha; do
  if [[ "$local_ref" == refs/heads/* ]]; then
    branch_name=${local_ref#refs/heads/}
    range=$([ "$remote_sha" = "$z40" ] && echo "$local_sha" || echo "$remote_sha..$local_sha")

    echo "Examining commits in range: $range"
    for commit in $(git log --format=%H "$range"); do
      msg=$(git log -1 --format=%B "$commit")
      if contains_wip "$msg"; then
        echo >&2 "ERROR: WIP commit detected: $commit"
        echo >&2 "$msg"
        exit 1
      fi
    done

    # Only after we know what commit to check out:
    before_hook 1 "$local_sha"

    echo "Running 'make lint'..."
    make lint || {
      echo "Linting failed. Please fix the issues before committing"
      exit 1
    }

    echo "Running 'make quick'..."
    make quick || {
      echo "Tests failed. Please fix the issues before committing"
      exit 1
    }

    exit 0 # trap will call after_hook
  fi
done <"$TEMP_FILE"

exit 0
