#! /usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <project_name>"
    exit 1
fi

TOPDIR=$(cd $(dirname $(readlink -f $0)) && pwd)

PROJECT_NAME="$1"
PROJECT_DIR="lattice/${PROJECT_NAME}"

SBT_TEMPLATE="${TOPDIR}/template_sbt.project"
SYN_TEMPLATE="${TOPDIR}/template_syn.prj"

mkdir -p "$PROJECT_DIR"
sed "s/PROJECT_NAME/${PROJECT_NAME}/g" "$SBT_TEMPLATE" > "${PROJECT_DIR}/${PROJECT_NAME}_sbt.project"
sed "s/PROJECT_NAME/${PROJECT_NAME}/g" "$SYN_TEMPLATE" > "${PROJECT_DIR}/${PROJECT_NAME}_syn.prj"
