ifndef IVERILOG_MK
IVERILOG_MK := 1

IVERILOG_FLAGS_SV   := -g2012
IVERILOG_FLAGS_DEFS := $(SYNTH_DEFS)
ifneq ($(filter-out 0,$(strip $(SVC_RV_DBG) $(SVC_RV_DBG_CPU) $(SVC_RV_DBG_IF) $(SVC_RV_DBG_ID) $(SVC_RV_DBG_EX) $(SVC_RV_DBG_MEM) $(SVC_RV_DBG_WB) $(SVC_RV_DBG_HAZ) $(SVC_RV_DBG_RVFI))),)
IVERILOG_FLAGS_DEFS += -DSVC_RV_DBG
endif
IVERILOG_FLAGS_WARN := -Wall -Wno-portbind -Wno-timescale
IVERILOG_FLAGS      := $(IVERILOG_FLAGS_SV) $(IVERILOG_FLAGS_DEFS) $(IVERILOG_FLAGS_WARN)
IVERILOG            := iverilog $(IVERILOG_FLAGS)

# VVP simulator command
VVP := vvp

endif
