#! /bin/sh

# spacing matters, if there are spaces after the , not all the options are parsed
# if this gets modified, replace the giant string with concatenation, but without spaces
verible-verilog-format --inplace --tryfromenv=indentation_spaces,column_limit,wrap_spaces,try_wrap_long_lines,assignment_statement_alignment,case_items_alignment,class_member_variable_alignment,distribution_items_alignment,enum_assignment_statement_alignment,formal_parameters_alignment,formal_parameters_indentation,module_net_variable_alignment,named_parameter_alignment,named_port_alignment,port_declarations_alignment,port_declarations_indentation,struct_union_members_alignment,wrap_end_else_clauses rtl/svc_sync_fifo.sv "$@"
