#! /bin/sh

verible-verilog-format                           \
  --inplace                                      \
  --tryfromenv="                                 \
      indentation_spaces,                        \
      column_limit,                              \
      wrap_spaces,                               \
      try_wrap_long_lines,                       \
      assignment_statement_alignment,            \
      case_items_alignment,                      \
      class_member_variable_alignment,           \
      distribution_items_alignment,i             \
      enum_assignment_statement_alignment,       \
      formal_parameters_alignment,               \
      formal_parameters_indentation,             \
      module_net_variable_alignment,             \
      named_parameter_alignment,                 \
      named_port_alignment,                      \
      port_declarations_alignment,               \
      port_declarations_indentation,             \
      struct_union_members_alignment,            \
      wrap_end_else_clauses"                     \
 "$@"
