#! /bin/sh

SVC_TOP=$(cd $(dirname $(readlink -f $0))/.. && pwd)
DEST_DIR=${1:-$(pwd)}

cp ${SVC_TOP}/flake.nix ${DEST_DIR}
cp ${SVC_TOP}/flake.lock ${DEST_DIR}
cp ${SVC_TOP}/.envrc ${DEST_DIR}
cp ${SVC_TOP}/.gitignore ${DEST_DIR}
cp ${SVC_TOP}/mk/makefile.template ${DEST_DIR}/Makefile

mkdir -p ${DEST_DIR}/rtl
mkdir -p ${DEST_DIR}/tb

mkdir -p ${DEST_DIR}/scripts
ln -sf ${SVC_TOP}/scripts/* ${DEST_DIR}/scripts
