#!/bin/sh

DEV_ARG="$1"
BAUD_ARG="$2"

BAUD=${BAUD_ARG:-115200}

# someday this could get fancy and iterate over the devices matching
# the right pattern and then use something like udevadm info -n <dev>
# to find one with the right FTDI chip on the other side, but for now,
# this is easy:
DEVS="${DEV_ARG:-/dev/ttyUSB1 /dev/cu.usbserial-21101}"

for DEV in $DEVS; do
  if [ -e "$DEV" ]; then
    echo "Found device: $DEV"

    # Set baud with stty since this works on both darwin and linux
    # (which take different socat flags for the same effect.)
    # Also disable HUPCL (Hang Up on CLose). When enabled, there
    # is duplicate output.
    stty -F $DEV $BAUD raw -hupcl
    socat -u "file:$DEV" -
    break
  fi
done
