#! /bin/sh -e

CMD=$(basename "$0")

# FIXME: this should be dynamic
PRJ_RTL_LIB="rtl"
SVC_RTL_LIB="svc/rtl"

echo $RTL_LIB

if [ $CMD = "y" ]; then
    YOSYS_CMD=$2
else
    YOSYS_CMD=$CMD
fi

yosys -DSYNTH_YOSYS -p "read_verilog -sv -I${PRJ_RTL_LIB} -I${SVC_RTL_LIB} $1; synth_ice40; $YOSYS_CMD"
